import { Router } from "express";
import Anthropic from "@anthropic-ai/sdk";
import { requireAuth, type AuthRequest } from "../middleware/auth.js";
import { supabase } from "../services/supabase.js";
import { cronReloadCallbacks } from "../services/tools.js";
import { triggerJobById } from "../services/scheduler.js";

const router = Router();

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// ── Default HTML template (used when client has no custom design) ─────────────
const DEFAULT_EMAIL_TEMPLATE = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:20px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
<!-- HEADER -->
<tr><td style="background:#2d1b4e;padding:28px 32px;">
<h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:700;">[CLIENT_NAME] Performance Update</h1>
<p style="margin:6px 0 0;color:#c9b8e8;font-size:14px;">[YESTERDAY_DATE] | Prepared by Melleka AI Strategist</p>
</td></tr>
<!-- GRADE BADGE ROW -->
<tr><td style="padding:24px 32px;background:#f9f7ff;border-bottom:1px solid #ede9f8;">
<table width="100%" cellpadding="0" cellspacing="0"><tr>
<td><span style="font-size:13px;color:#6b6b6b;text-transform:uppercase;letter-spacing:0.5px;">Yesterday's Grade</span>
<br><span style="font-size:48px;font-weight:900;color:#2d1b4e;">[GRADE]</span></td>
<td align="right" style="vertical-align:bottom;padding-bottom:8px;">
<span style="background:[GRADE_COLOR];color:#fff;padding:6px 16px;border-radius:20px;font-size:14px;font-weight:600;">ROAS [YESTERDAY_ROAS]x</span>
</td></tr></table>
</td></tr>
<!-- PERFORMANCE TABLE -->
<tr><td style="padding:24px 32px;">
<h2 style="margin:0 0 16px;color:#2d1b4e;font-size:16px;">Performance Summary</h2>
<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
<tr style="background:#2d1b4e;color:#fff;">
<th style="padding:10px 14px;text-align:left;font-size:13px;">Period</th>
<th style="padding:10px 14px;text-align:right;font-size:13px;">Spend</th>
<th style="padding:10px 14px;text-align:right;font-size:13px;">Revenue</th>
<th style="padding:10px 14px;text-align:right;font-size:13px;">ROAS</th>
</tr>
[PERFORMANCE_TABLE_ROWS]
</table>
</td></tr>
<!-- GRADE SCALE -->
<tr><td style="padding:0 32px 20px;">
<p style="margin:0 0 8px;font-size:12px;color:#888;text-transform:uppercase;letter-spacing:0.5px;">Grade Scale</p>
<table cellpadding="0" cellspacing="4"><tr>
<td style="background:#1a7f4b;color:#fff;padding:4px 8px;border-radius:3px;font-size:11px;font-weight:600;">A+ 5x+</td>
<td style="background:#1a7f4b;color:#fff;padding:4px 8px;border-radius:3px;font-size:11px;font-weight:600;">A 4-5x</td>
<td style="background:#5cb85c;color:#fff;padding:4px 8px;border-radius:3px;font-size:11px;font-weight:600;">B+ 3.5-4x</td>
<td style="background:#5cb85c;color:#fff;padding:4px 8px;border-radius:3px;font-size:11px;font-weight:600;">B 3-3.5x</td>
<td style="background:#f5a623;color:#fff;padding:4px 8px;border-radius:3px;font-size:11px;font-weight:600;">C 2.5-3x</td>
<td style="background:#f5a623;color:#fff;padding:4px 8px;border-radius:3px;font-size:11px;font-weight:600;">D 2-2.5x</td>
<td style="background:#e74c3c;color:#fff;padding:4px 8px;border-radius:3px;font-size:11px;font-weight:600;">F &lt;2x</td>
</tr></table>
</td></tr>
<!-- STRATEGIST NOTES -->
<tr><td style="padding:0 32px 28px;">
<div style="background:#f9f7ff;border-left:4px solid #2d1b4e;padding:16px 20px;border-radius:0 6px 6px 0;">
<p style="margin:0 0 6px;font-size:12px;font-weight:700;text-transform:uppercase;color:#2d1b4e;letter-spacing:0.5px;">Strategist Notes</p>
<p style="margin:0;font-size:14px;color:#333;line-height:1.6;">[STRATEGIST_NOTES]</p>
</div>
</td></tr>
<!-- FOOTER -->
<tr><td style="background:#2d1b4e;padding:16px 32px;text-align:center;">
<p style="margin:0;color:#c9b8e8;font-size:12px;">Generated by Melleka AI Strategist | Melleka Marketing</p>
</td></tr>
</table>
</td></tr></table>
</body></html>`;

// ── Build cron task prompt ────────────────────────────────────────────────────
function buildCronTask(row: {
  client_name: string;
  google_ads_account_id?: string | null;
  email_recipients: string[];
  email_send_mode?: string;
  email_design?: string | null;
  email_design_locked?: boolean;
  template_notes?: string | null;
}): string {
  const {
    client_name,
    google_ads_account_id,
    email_recipients,
    email_send_mode = "single_email",
    email_design,
    email_design_locked,
    template_notes,
  } = row;

  const accountLine = google_ads_account_id
    ? `Account ID: ${google_ads_account_id}`
    : `Search by client name: ${client_name}`;

  // Build email delivery instructions
  let emailStep: string;
  if (email_send_mode === "separate_emails") {
    const recipientList = email_recipients.join(", ");
    emailStep = `STEP 3 — Send SEPARATE individual emails to each recipient:
CRITICAL: Pass the completed HTML DIRECTLY as the body. Do NOT wrap in markdown code fences. Body MUST start with <!DOCTYPE html>.
Recipients: ${recipientList}
Send one email per person. Do NOT CC anyone. Each recipient gets their own copy.
From: "Melleka AI Strategist <ai@listing.melleka.com>"
Subject: "${client_name} ROAS Brief | [yesterday's date] | [ROAS]x | Grade [letter grade]"`;
  } else {
    const toEmail = email_recipients[0] ?? "";
    const ccEmails = email_recipients.slice(1).join(", ");
    emailStep = `STEP 3 — Send ONE email (do NOT send multiple):
CRITICAL: Pass the completed HTML DIRECTLY as the body. Do NOT wrap in markdown code fences. Body MUST start with <!DOCTYPE html>.
To: ${toEmail}${ccEmails ? `\nCC: ${ccEmails}` : ""}
From: "Melleka AI Strategist <ai@listing.melleka.com>"
Subject: "${client_name} ROAS Brief | [yesterday's date] | [ROAS]x | Grade [letter grade]"`;
  }

  // Build design instructions
  let designStep: string;
  if (email_design && email_design_locked) {
    const notesLine = template_notes ? `Fill guidance: ${template_notes}\n\n` : "";
    designStep = `STEP 2 — Fill the LOCKED DESIGN TEMPLATE below with live data.
RULES:
- Do NOT change any colors, fonts, layout, or HTML structure
- Find every ALL_CAPS_PLACEHOLDER token in the HTML (e.g. DATA_DATE_PLACEHOLDER, GRADE_PLACEHOLDER, YESTERDAY_ROAS, CAMPAIGN_TABLE_PLACEHOLDER, SECTION_1_PLACEHOLDER, etc.) and replace it with the correct data from STEP 1
- Grade scale, color rules, and ROAS thresholds are in the fill guidance below or visible in the HTML grade scale section
- After filling, the HTML must still start with <!DOCTYPE html>

${notesLine}LOCKED TEMPLATE:
${email_design}

== Fill the above template completely before proceeding to STEP 3 ==`;
  } else {
    designStep = `STEP 2 — Build HTML email using the standard Melleka performance email design.
Fill in all data. Follow these rules exactly:

Grade thresholds (yesterday ROAS): A+(5x+), A(4-5x), B+(3.5-4x), B(3-3.5x), C(2.5-3x), D(2-2.5x), F(<2x)
ROAS colors: 4x+=#1a7f4b, 3-4x=#5cb85c, 2-3x=#f5a623, below 2x=#e74c3c

Standard design template:
${DEFAULT_EMAIL_TEMPLATE}

Strategist Notes: Write 2-3 insightful sentences about performance trends.${template_notes ? `\nAdditional notes guidance: ${template_notes}` : ""}`;
  }

  return `AUTO CLIENT UPDATE — ${client_name}
IMPORTANT: This task sends email ONLY. Do NOT post to Slack. Do NOT call slack_post under any circumstances.

STEP 0 — DEDUP CHECK:
Call supabase_query: table="auto_client_updates", filter client_name="${client_name}", select="last_sent_at" — fetch ONLY this column (not all columns — the row is very large and will confuse context).
Call get_current_date to get today's date.
If last_sent_at already matches today's date: stop immediately. Log "Already sent today." Do not continue.

STEP 1 — Pull Google Ads performance data:
${accountLine}
Filter: ENABLED campaigns only.
Pull 4 windows: Yesterday, 7-Day, 14-Day, 30-Day.
ROAS = SUM(conversions_value) / SUM(cost_micros / 1000000).

${designStep}

${emailStep}
Send email ONLY to the recipients listed above. Do NOT add, remove, or change any recipients. Do NOT post to Slack.

STEP 4 — Update last_sent_at:
Call supabase_update on table "auto_client_updates": set last_sent_at = today's date WHERE client_name = "${client_name}"

STEP 5 — Log completion to super_agent_task.`;
}

// ── GET /api/auto-client-updates ─────────────────────────────────────────────
router.get("/", requireAuth, async (_req: AuthRequest, res) => {
  try {
    const { data, error } = await supabase
      .from("auto_client_updates")
      .select("*")
      .order("client_name", { ascending: true });

    if (error) { res.status(500).json({ error: error.message }); return; }

    const cronJobIds = (data ?? []).map((r: any) => r.cron_job_id).filter(Boolean);
    let cronMap: Record<string, any> = {};
    if (cronJobIds.length > 0) {
      const { data: cronRows } = await supabase
        .from("team_cron_jobs")
        .select("id, last_run, next_run, name")
        .in("id", cronJobIds);
      for (const row of cronRows ?? []) cronMap[row.id] = row;
    }

    const enriched = (data ?? []).map((r: any) => {
      const cronJob = r.cron_job_id ? cronMap[r.cron_job_id] : null;
      return {
        ...r,
        last_run: cronJob?.last_run ?? null,
        next_run: cronJob?.next_run ?? null,
        // true = created by this system, safe to auto-update task prompt
        // false = externally managed (e.g. existing Vegamour cron jobs) — protect from task rewrites
        cron_job_system_managed: cronJob ? (cronJob.name ?? "").startsWith("Auto Client Update:") : false,
      };
    });

    res.json(enriched);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ── POST /api/auto-client-updates ────────────────────────────────────────────
router.post("/", requireAuth, async (req: AuthRequest, res) => {
  try {
    const {
      client_name, google_ads_account_id, email_recipients,
      cron_expr, enabled, email_send_mode, email_design,
      email_design_locked, template_notes,
    } = req.body;

    if (!client_name || typeof client_name !== "string") {
      res.status(400).json({ error: "client_name is required" });
      return;
    }

    const recipients: string[] = Array.isArray(email_recipients) ? email_recipients : [];
    const expr = cron_expr || "0 8 * * 1-5";
    const isEnabled = enabled !== false;

    const { data: newRow, error: insertErr } = await supabase
      .from("auto_client_updates")
      .insert({
        client_name: client_name.trim(),
        google_ads_account_id: google_ads_account_id?.trim() || null,
        email_recipients: recipients,
        cron_expr: expr,
        enabled: isEnabled,
        email_send_mode: email_send_mode || "single_email",
        email_design: email_design || null,
        email_design_locked: !!email_design_locked,
        template_notes: template_notes || null,
      })
      .select()
      .single();

    if (insertErr) { res.status(500).json({ error: insertErr.message }); return; }

    const task = buildCronTask({
      client_name: newRow.client_name,
      google_ads_account_id: newRow.google_ads_account_id,
      email_recipients: recipients,
      email_send_mode: newRow.email_send_mode,
      email_design: newRow.email_design,
      email_design_locked: newRow.email_design_locked,
      template_notes: newRow.template_notes,
    });

    const { data: cronRow, error: cronErr } = await supabase
      .from("team_cron_jobs")
      .insert({
        member_name: "system",
        name: `Auto Client Update: ${newRow.client_name}`,
        cron_expr: expr,
        task,
        enabled: isEnabled,
      })
      .select()
      .single();

    if (cronErr) {
      console.error("[auto-client-updates] Failed to create cron job:", cronErr.message);
    } else {
      await supabase.from("auto_client_updates").update({ cron_job_id: cronRow.id }).eq("id", newRow.id);
      cronReloadCallbacks.forEach((cb) => cb());
    }

    res.status(201).json({ ...newRow, cron_job_id: cronRow?.id ?? null });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ── PATCH /api/auto-client-updates/:id ───────────────────────────────────────
router.patch("/:id", requireAuth, async (req: AuthRequest, res) => {
  try {
    const { id } = req.params;
    const {
      client_name, google_ads_account_id, email_recipients,
      cron_expr, enabled, email_send_mode, email_design,
      email_design_locked, template_notes,
    } = req.body;

    const { data: existing, error: fetchErr } = await supabase
      .from("auto_client_updates")
      .select("*")
      .eq("id", id)
      .maybeSingle();

    if (fetchErr || !existing) { res.status(404).json({ error: "Not found" }); return; }

    const updates: Record<string, any> = { updated_at: new Date().toISOString() };
    if (client_name !== undefined) updates.client_name = client_name.trim();
    if (google_ads_account_id !== undefined) updates.google_ads_account_id = google_ads_account_id?.trim() || null;
    if (email_recipients !== undefined) updates.email_recipients = email_recipients;
    if (cron_expr !== undefined) updates.cron_expr = cron_expr;
    if (enabled !== undefined) updates.enabled = enabled;
    if (email_send_mode !== undefined) updates.email_send_mode = email_send_mode;
    if (email_design !== undefined) updates.email_design = email_design;
    if (email_design_locked !== undefined) updates.email_design_locked = email_design_locked;
    if (template_notes !== undefined) updates.template_notes = template_notes;

    const { data: updated, error: updateErr } = await supabase
      .from("auto_client_updates")
      .update(updates)
      .eq("id", id)
      .select()
      .single();

    if (updateErr) { res.status(500).json({ error: updateErr.message }); return; }

    if (existing.cron_job_id) {
      // Check if this cron job was created by this system or externally (e.g. existing Vegamour jobs)
      const { data: linkedCronJob } = await supabase
        .from("team_cron_jobs")
        .select("name")
        .eq("id", existing.cron_job_id)
        .maybeSingle();

      const systemManaged = (linkedCronJob?.name ?? "").startsWith("Auto Client Update:");

      let cronUpdates: Record<string, any>;
      if (systemManaged) {
        // Full update: regenerate task prompt + sync all fields
        const newTask = buildCronTask({
          client_name: updated.client_name,
          google_ads_account_id: updated.google_ads_account_id,
          email_recipients: updated.email_recipients,
          email_send_mode: updated.email_send_mode,
          email_design: updated.email_design,
          email_design_locked: updated.email_design_locked,
          template_notes: updated.template_notes,
        });
        cronUpdates = { task: newTask };
        if (client_name !== undefined) cronUpdates.name = `Auto Client Update: ${updated.client_name}`;
        if (cron_expr !== undefined) cronUpdates.cron_expr = updated.cron_expr;
        if (enabled !== undefined) cronUpdates.enabled = updated.enabled;
      } else {
        // External cron job: sync enabled/schedule + recipients (via targeted string replacement)
        cronUpdates = {};
        if (enabled !== undefined) cronUpdates.enabled = updated.enabled;
        if (cron_expr !== undefined) cronUpdates.cron_expr = updated.cron_expr;

        // If recipients changed, patch To/CC lines directly in the task text
        if (email_recipients !== undefined && Array.isArray(updated.email_recipients)) {
          const { data: taskRow } = await supabase
            .from("team_cron_jobs")
            .select("task")
            .eq("id", existing.cron_job_id)
            .maybeSingle();

          if (taskRow?.task) {
            const toEmail = updated.email_recipients[0] ?? "";
            const ccEmails = updated.email_recipients.slice(1).join(", ");
            let newTask = taskRow.task;
            // Replace To: line
            newTask = newTask.replace(/^To: .+$/m, `To: ${toEmail}`);
            // Replace CC: line (remove it if no CC, add it if missing)
            if (ccEmails) {
              if (/^CC: .+$/m.test(newTask)) {
                newTask = newTask.replace(/^CC: .+$/m, `CC: ${ccEmails}`);
              } else {
                newTask = newTask.replace(/^(To: .+)$/m, `$1\nCC: ${ccEmails}`);
              }
            } else {
              newTask = newTask.replace(/^CC: .+\n?/m, "");
            }
            cronUpdates.task = newTask;
          }
        }
      }

      if (Object.keys(cronUpdates).length > 0) {
        const { error: cronErr } = await supabase
          .from("team_cron_jobs")
          .update(cronUpdates)
          .eq("id", existing.cron_job_id);

        if (cronErr) {
          console.error("[auto-client-updates] Failed to sync cron job:", cronErr.message);
        }
      }

      cronReloadCallbacks.forEach((cb) => cb());
    }

    res.json(updated);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ── DELETE /api/auto-client-updates/:id ──────────────────────────────────────
router.delete("/:id", requireAuth, async (req: AuthRequest, res) => {
  try {
    const { data: existing } = await supabase
      .from("auto_client_updates")
      .select("cron_job_id")
      .eq("id", req.params.id)
      .maybeSingle();

    const { error } = await supabase.from("auto_client_updates").delete().eq("id", req.params.id);
    if (error) { res.status(500).json({ error: error.message }); return; }

    if (existing?.cron_job_id) {
      await supabase.from("team_cron_jobs").delete().eq("id", existing.cron_job_id);
      cronReloadCallbacks.forEach((cb) => cb());
    }

    res.json({ ok: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ── POST /api/auto-client-updates/:id/ai-design ──────────────────────────────
// AI modifies the HTML design based on natural language instructions
router.post("/:id/ai-design", requireAuth, async (req: AuthRequest, res) => {
  try {
    const { instructions, current_design } = req.body;
    if (!instructions) { res.status(400).json({ error: "instructions is required" }); return; }

    const baseDesign = current_design || DEFAULT_EMAIL_TEMPLATE;

    const response = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 8192,
      messages: [{
        role: "user",
        content: `You are an HTML email designer. Modify this HTML email template based on these instructions.

Instructions: ${instructions}

Rules:
- Return ONLY the complete modified HTML document, no explanation, no markdown fences
- Keep all placeholder tokens like [CLIENT_NAME], [GRADE], [YESTERDAY_ROAS], [PERFORMANCE_TABLE_ROWS], [STRATEGIST_NOTES], [YESTERDAY_DATE], [GRADE_COLOR]
- Keep the email rendering-safe (inline styles, table-based layout, no JS)
- Preserve email client compatibility

Current HTML:
${baseDesign}`,
      }],
    });

    const html = (response.content[0] as any)?.text ?? "";
    res.json({ html });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// ── POST /api/auto-client-updates/:id/test ───────────────────────────────────
// Triggers the actual production cron job with all dedup cleared.
// Pulls real Google Ads data, sends real email — identical to the scheduled run.
router.post("/:id/test", requireAuth, async (req: AuthRequest, res) => {
  try {
    const { data: client } = await supabase
      .from("auto_client_updates")
      .select("*")
      .eq("id", req.params.id)
      .maybeSingle();

    if (!client) { res.status(404).json({ error: "Not found" }); return; }
    if (!client.cron_job_id) {
      res.status(400).json({ error: "No cron job linked to this client." });
      return;
    }

    // Clear our own dedup flag
    await supabase
      .from("auto_client_updates")
      .update({ last_sent_at: null })
      .eq("id", client.id);

    // Fetch the linked cron job to detect external dedup keys
    const { data: cronJob } = await supabase
      .from("team_cron_jobs")
      .select("task")
      .eq("id", client.cron_job_id)
      .maybeSingle();

    // Parse any strategist_config dedup key from the task text and reset it
    if (cronJob?.task) {
      const match = cronJob.task.match(/config_key\s*=\s*["']([^"']+)["']/);
      if (match) {
        const dedupKey = match[1];
        await supabase
          .from("strategist_config")
          .update({ config_value: "2000-01-01" })
          .eq("config_key", dedupKey);
      }
    }

    // Trigger the real production cron job — identical to the scheduled run
    const result = await triggerJobById(client.cron_job_id);
    if (!result.ok) {
      res.status(500).json({ error: result.error ?? "Failed to trigger job" });
      return;
    }

    res.json({ ok: true, message: "Job triggered — real email sending now with live data." });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
